@apiUrl = http://localhost:3000/api
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUyMDA0MTA2LCJleHAiOjE3NTIwMDc3MDZ9.CnczmiNCtfI6fpvs8I3WusJ8YW3IFIl-h70xKZVNlt0

GET {{apiUrl}}

###

GET {{apiUrl}}/users
Authorization: {{token}}

###

GET {{apiUrl}}/users/1

###

POST {{apiUrl}}/auth/signup
Content-Type: application/json

{
  "username": "John",
  "email": "john@tester.de",
  "password": "wick"
}

###

POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  "email": "john@tester.de",
  "password": "wick"
}

###

POST {{apiUrl}}/auth/refresh