@apiUrl = http://localhost:3000/api
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzUyNDM1ODgxLCJleHAiOjE3NTI0MzY0ODF9.QOneiVlPx48JEdIofvwjhnyUYWc31iBy8vk1i_ikfGw

GET {{apiUrl}}

###

GET {{apiUrl}}/users
Authorization: {{token}}

###

GET {{apiUrl}}/users/1

###

POST {{apiUrl}}/auth/signup
Content-Type: application/json

{
  "username": "max",
  "email": "max@test.de",
  "password": "test"
}

###

POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  "email": "max@test.de",
  "password": "test"
}

###

POST {{apiUrl}}/auth/refresh

###

GET {{apiUrl}}/games
Authorization: {{token}}